# Site settings
title: "Muhammad Abdur Rabb | Data Analyst | Machine Learning"  # Replace with your name or site title
description: "A personal portfolio showcasing my work and projects."  # A brief description of your site
baseurl: ""  # Leave empty unless your site is published in a subdirectory
url: https://github.com/m-abdur-rabb/m-abdur-rabb.github.io"  # Your GitHub Pages URL (replace with your GitHub username)

# GitHub settings
repository: "m-abdur-rabb/m-abdur-rabb.github.io"  # Replace with your GitHub username and repository name

# Build settings
markdown: kramdown  # The default markdown processor (not needed for plain HTML but included by default)
theme: null  # No theme since you're using custom HTML/CSS/JS

# Exclude unnecessary files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor

# Plugins (optional, for SEO or sitemap if needed in the future)

# Include specific directories if necessary
include:
  - _pages  # Include this if you have a custom folder for pages

# Permalinks for pretty URLs (optional)
permalink: pretty

# SEO settings (optional)
